spring:
  mvc:
    async:
      request-timeout: 5s
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sitesafety_db
    username: kdt_user
    password: kdt1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
mybatis:
  # mapper XML 위치
  mapper-locations: classpath:/mapper/**/*.xml
  # VO / DTO 패키지 (resultType, parameterType 생략용)
  type-aliases-package: org.example.nova.sitesafety.model
  configuration:
    # snake_case → camelCase 자동 매핑
    map-underscore-to-camel-case: true